// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQ.CDT_SINAI.API.Data;

#nullable disable

namespace SQ.CDT_SINAI.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116140733_AddIsComplianceToDocumentTypes")]
    partial class AddIsComplianceToDocumentTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BrandEstablishment", b =>
                {
                    b.Property<int>("BrandsId")
                        .HasColumnType("int");

                    b.Property<int>("EstablishmentsId")
                        .HasColumnType("int");

                    b.HasKey("BrandsId", "EstablishmentsId");

                    b.HasIndex("EstablishmentsId");

                    b.ToTable("BrandEstablishment");
                });

            modelBuilder.Entity("CollaboratorEstablishment", b =>
                {
                    b.Property<int>("CollaboratorsId")
                        .HasColumnType("int");

                    b.Property<int>("EstablishmentsId")
                        .HasColumnType("int");

                    b.HasKey("CollaboratorsId", "EstablishmentsId");

                    b.HasIndex("EstablishmentsId");

                    b.ToTable("CollaboratorEstablishment");
                });

            modelBuilder.Entity("CollaboratorSpecialization", b =>
                {
                    b.Property<int>("CollaboratorsId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationsId")
                        .HasColumnType("int");

                    b.HasKey("CollaboratorsId", "SpecializationsId");

                    b.HasIndex("SpecializationsId");

                    b.ToTable("CollaboratorSpecialization");
                });

            modelBuilder.Entity("DocumentTypeEstablishmentType", b =>
                {
                    b.Property<int>("EstablishmentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("NecessaryDocumentsId")
                        .HasColumnType("int");

                    b.HasKey("EstablishmentTypeId", "NecessaryDocumentsId");

                    b.HasIndex("NecessaryDocumentsId");

                    b.ToTable("EstablishmentTypeNecessaryDocuments", (string)null);
                });

            modelBuilder.Entity("DocumentTypeEstablishmentType1", b =>
                {
                    b.Property<int>("ClosingDocumentsId")
                        .HasColumnType("int");

                    b.Property<int>("EstablishmentType1Id")
                        .HasColumnType("int");

                    b.HasKey("ClosingDocumentsId", "EstablishmentType1Id");

                    b.HasIndex("EstablishmentType1Id");

                    b.ToTable("EstablishmentTypeClosingDocuments", (string)null);
                });

            modelBuilder.Entity("EstablishmentEstablishmentType", b =>
                {
                    b.Property<int>("EstablishmentTypesId")
                        .HasColumnType("int");

                    b.Property<int>("EstablishmentsId")
                        .HasColumnType("int");

                    b.HasKey("EstablishmentTypesId", "EstablishmentsId");

                    b.HasIndex("EstablishmentsId");

                    b.ToTable("EstablishmentEstablishmentType");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.Collaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressNeighborhood")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressStreet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressZipCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfessionalLicense")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Collaborators");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.DocumentRenewalLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<int>("EstablishmentDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NewExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OldExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RenewalDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentDocumentId");

                    b.ToTable("DocumentRenewalLogs");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCompliance")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsibleArea")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.Establishment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Regional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Establishments");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.EstablishmentDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutomaticRenewal")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EmissionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstablishmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Justification")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProtocolNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("RenewalMonths")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("EstablishmentId");

                    b.ToTable("EstablishmentDocuments");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.EstablishmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServiceLocationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstablishmentTypes");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Cip")
                        .HasColumnType("longtext");

                    b.Property<string>("ClientAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ClientBirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ClientCpf")
                        .HasColumnType("longtext");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ClientName")
                        .HasColumnType("longtext");

                    b.Property<string>("ClientPhone")
                        .HasColumnType("longtext");

                    b.Property<int>("ClientType")
                        .HasColumnType("int");

                    b.Property<int>("ContactMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorCrm")
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorName")
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorPhone1")
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorPhone2")
                        .HasColumnType("longtext");

                    b.Property<string>("HealthInsurance")
                        .HasColumnType("longtext");

                    b.Property<string>("InvolvedArea")
                        .HasColumnType("longtext");

                    b.Property<string>("InvolvedBrand")
                        .HasColumnType("longtext");

                    b.Property<string>("InvolvedRegional")
                        .HasColumnType("longtext");

                    b.Property<string>("LocationOrUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("ProtocolNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ReporterContact")
                        .HasColumnType("longtext");

                    b.Property<int?>("ReporterId")
                        .HasColumnType("int");

                    b.Property<string>("ReporterName")
                        .HasColumnType("longtext");

                    b.Property<string>("Response")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecondaryContactName")
                        .HasColumnType("longtext");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetArea")
                        .HasColumnType("longtext");

                    b.Property<string>("TargetAreaOrProfessional")
                        .HasColumnType("longtext");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReporterId");

                    b.HasIndex("TargetId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Coordenador"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Colaborador"
                        });
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "View",
                            Module = "Collaborator",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 2,
                            Action = "Create",
                            Module = "Collaborator",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Action = "Edit",
                            Module = "Collaborator",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Action = "View",
                            Module = "Establishment",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            Action = "View",
                            Module = "Collaborator",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("BrandEstablishment", b =>
                {
                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Establishment", null)
                        .WithMany()
                        .HasForeignKey("EstablishmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollaboratorEstablishment", b =>
                {
                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Collaborator", null)
                        .WithMany()
                        .HasForeignKey("CollaboratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Establishment", null)
                        .WithMany()
                        .HasForeignKey("EstablishmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollaboratorSpecialization", b =>
                {
                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Collaborator", null)
                        .WithMany()
                        .HasForeignKey("CollaboratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Specialization", null)
                        .WithMany()
                        .HasForeignKey("SpecializationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocumentTypeEstablishmentType", b =>
                {
                    b.HasOne("SQ.CDT_SINAI.Shared.Models.EstablishmentType", null)
                        .WithMany()
                        .HasForeignKey("EstablishmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQ.CDT_SINAI.Shared.Models.DocumentType", null)
                        .WithMany()
                        .HasForeignKey("NecessaryDocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocumentTypeEstablishmentType1", b =>
                {
                    b.HasOne("SQ.CDT_SINAI.Shared.Models.DocumentType", null)
                        .WithMany()
                        .HasForeignKey("ClosingDocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQ.CDT_SINAI.Shared.Models.EstablishmentType", null)
                        .WithMany()
                        .HasForeignKey("EstablishmentType1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EstablishmentEstablishmentType", b =>
                {
                    b.HasOne("SQ.CDT_SINAI.Shared.Models.EstablishmentType", null)
                        .WithMany()
                        .HasForeignKey("EstablishmentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Establishment", null)
                        .WithMany()
                        .HasForeignKey("EstablishmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.Collaborator", b =>
                {
                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Role", "Role")
                        .WithMany("Collaborators")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.DocumentRenewalLog", b =>
                {
                    b.HasOne("SQ.CDT_SINAI.Shared.Models.EstablishmentDocument", "EstablishmentDocument")
                        .WithMany()
                        .HasForeignKey("EstablishmentDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstablishmentDocument");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.EstablishmentDocument", b =>
                {
                    b.HasOne("SQ.CDT_SINAI.Shared.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Establishment", "Establishment")
                        .WithMany("Documents")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.Incident", b =>
                {
                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Collaborator", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId");

                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Collaborator", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId");

                    b.Navigation("Reporter");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.RolePermission", b =>
                {
                    b.HasOne("SQ.CDT_SINAI.Shared.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.Establishment", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("SQ.CDT_SINAI.Shared.Models.Role", b =>
                {
                    b.Navigation("Collaborators");
                });
#pragma warning restore 612, 618
        }
    }
}
